// <auto-generated />
using BelemTour.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelemTour.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BelemTour.Model.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("categoria");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("imagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Tempo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tempo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("destino");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Tur",
                            Imagem = "http://www.altaestacaoturismo.com.br/images/content/destinos/14-1.jpg",
                            Nome = "Salinopolis",
                            Tempo = "5 Dias",
                            Valor = 200.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Passeios Regulares",
                            Imagem = "https://scontent.fsjk9-1.fna.fbcdn.net/v/t1.6435-9/37023389_1329318750504085_4156171523704487936_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=c2f564&_nc_ohc=Q3g9qmEooD4AX_vXbAf&_nc_ht=scontent.fsjk9-1.fna&oh=00_AfA-xe3b64XOLbrlCoscdctcAM2EQZIXjKj2U1Y73aZ0uw&oe=65C675E6",
                            Nome = "Mosqueiro",
                            Tempo = "1 semana",
                            Valor = 499.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Passeios Regulares",
                            Imagem = "https://s2-g1.glbimg.com/8csOy6Wslb86EiUyE_oloIM5oOQ=/0x0:620x465/1008x0/smart/filters:strip_icc()/s.glbimg.com/jo/g1/f/original/2012/07/25/vistaaereapraia_da_princesa-henriquefelicio.jpg",
                            Nome = "Algodoal",
                            Tempo = "2 semana",
                            Valor = 900.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Passeios Regulares",
                            Imagem = "https://www.ferias.tur.br/imgs/4682/maruda/g_maruda-pa-dsc_0080.jpg",
                            Nome = "Marudá",
                            Tempo = "15 Dias",
                            Valor = 500.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Passeios Regulares",
                            Imagem = "https://scontent.fsjk9-1.fna.fbcdn.net/v/t39.30808-6/310595670_542403674555503_1563832596458789831_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=783fdb&_nc_ohc=bSXETuLcMNIAX-1Mhib&_nc_ht=scontent.fsjk9-1.fna&oh=00_AfDwTz-DNaBCcBSCeFCMtLGRzbZ62BdohuVXtM5yFtZ0eg&oe=65A4476F",
                            Nome = "Ajuruteua",
                            Tempo = "3 semana",
                            Valor = 1500.00m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Tur",
                            Imagem = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/0c/9a/58/praia-do-outeiro.jpg?w=900&h=600&s=1",
                            Nome = "Outeiro",
                            Tempo = " 10 dias",
                            Valor = 400.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
